### PR TITLE
James ball clic issue 409

### PR DESCRIPTION
**Pull request by james-ball-qualcomm**
Note that I created a new branch off main called "issue 409" but somehow managed to make the changes in my old "issue 411" branch that already got merged into main. Sorry, still getting up to speed on GitHub. I don't think I've done any harm but let me know if otherwise.

Anyways, preparing to renaming 'x' CSRs to 'm' in smclic (i.e., issue 409). Before doing this, noticed that newer CSRs such as indirect CSRs and the cliccfg ext don't have formating of CSR names consistent with rest of CLIC. So, I'm doing this first PR so you can see those changes and then I'll make the issue 409 changes and push them. Then hopefully one PR review and approval can be used to push all this into main.

### CODE REVIEW

**Comment by christian-herber-nxp** [comment]
You can see that you old commits are part of the history in this PR.
I think it would be best to switch to the new branch. You can e.g. git cherry-pick the commit you want to keep.

**Comment by christian-herber-nxp** [comment]
Changes look fine.

**Comment by james-ball-qualcomm** [comment]
This should be ready to merge into the main branch. I'd recommend we do this soon so we can make follow-on changes identified in the new issues I created today.

**Comment by christian-herber-nxp** [comment]
> This should be ready to merge into the main branch. I'd recommend we do this soon so we can make follow-on changes identified in the new issues I created today.

The commit history in this is still a bis messy. I would suggest to clean this using your favorite git method.

**Comment by james-ball-qualcomm** [comment]
I have no idea how to clean this up in Git (i.e., don't have a favorite method). Is there someone who can help with this? Otherwise, I'm not sure how I'll make progress on this.

**Comment by christian-herber-nxp** [comment]
I am back in office Friday. Might look into it Thursday. 
If you want to merge before, just make sure to squash and make a nice commit message for the merge commit. Then at least what ends up in master will be clean.

**Comment by james-ball-qualcomm** [comment]
Thanks for your offer of assistance.

**Pull request closed without merging**
